-- Exploratory Data Analysis --
-- =====================
-- Database Exploration
-- =====================

-- Explore all objects in the database
	SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dim_customers'

-- =======================
-- Dimensions Exploration
-- =======================

-- Explore all countries our customers come from
	SELECT DISTINCT country FROM retail.dim_customers

-- Explore all categories "The major Divisions"
	SELECT DISTINCT category, subcategory, product_name FROM retail.dim_products
	ORDER BY 1,2,3

-- =================
-- Date Exploration
-- =================

-- Find the date of the first and last order
-- How many years of sales are available
	SELECT 
		MIN(order_date) AS first_order, 
		MAX(order_date) last_order,
		DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS interval_order_years
	FROM retail.fact_sales

-- Find the youngest and oldest customers
	SELECT 
		MIN(birthdate) AS oldest_birthdate,
		DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_customer,
		MAX(birthdate) AS youngest_birthdate,
		DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_customer
	FROM retail.dim_customers

-- =====================
-- Measures Exploration
-- =====================
	SELECT * FROM retail.dim_customers;
	SELECT * FROM retail.dim_products;
	SELECT * FROM retail.fact_sales;

-- Find the Total Sales
	SELECT SUM(sales_amount) AS Total_Sales
	FROM retail.fact_sales

-- Find how many items are sold
	SELECT SUM(quantity) AS Total_Quantity
	FROM retail.fact_sales

-- Find the average selling price
	SELECT AVG(price) AS Avg_Price
	FROM retail.fact_sales

-- Find the total number of orders
	SELECT COUNT(order_number) AS Total_Orders
	FROM retail.fact_sales;
	SELECT COUNT(DISTINCT order_number) AS Total_Orders
	FROM retail.fact_sales;

-- Find the total number of products
	SELECT COUNT(product_key) AS Total_Products 
	FROM retail.dim_products

-- Find the total number of customers
	SELECT COUNT(customer_key) AS Total_Customers
	FROM retail.dim_customers

-- Find the total number of customers that has placed an order
	SELECT COUNT(DISTINCT customer_key) FROM retail.fact_sales

-- Generate report that shows all key metrics of the business 
	SELECT 'Total Sales' AS Measure_Name, SUM(sales_amount) AS Measure_Value FROM retail.fact_sales
	UNION ALL
	SELECT 'Total Quantity', SUM(quantity) FROM retail.fact_sales
	UNION ALL
	SELECT 'Average Price', AVG(price) FROM retail.fact_sales
	UNION ALL
	SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM retail.fact_sales
	UNION ALL
	SELECT 'Total Products', COUNT(product_key) FROM retail.dim_products
	UNION ALL
	SELECT 'Total Customers', COUNT(customer_key) FROM retail.dim_customers

-- ===================
-- Magnitude Analysis 
-- ===================

-- Measures by Dimensions
-- Find total customers by countries
	SELECT country, COUNT(customer_id) AS total_customers
	FROM retail.dim_customers
	GROUP BY country
	ORDER BY total_customers DESC

-- Find total customers by gender
	SELECT * FROM gold.dim_customers;
	SELECT gender, COUNT(customer_id) AS total_customers 
	FROM retail.dim_customers
	GROUP BY gender 
	ORDER BY total_customers DESC

-- Find total products by category
	SELECT category, COUNT(product_name) AS total_products
	FROM retail.dim_products
	GROUP BY category
	ORDER BY category DESC

-- What is the average costs in each category?
	SELECT category, AVG(cost) avg_cost 
	FROM retail.dim_products
	GROUP BY category
	ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
	SELECT dp. category, SUM(fs.sales_amount) AS total_revenue
	FROM retail.fact_sales AS fs
	LEFT JOIN retail.dim_products AS dp
		ON fs.product_key = dp.product_key
	GROUP BY dp.category
	ORDER BY total_revenue DESC

-- Find the total revenue is generated by each customer
	SELECT dc.customer_id, dc.first_name, dc.last_name,
	SUM(sales_amount) AS total_revenue
	FROM retail.fact_sales AS fs
	JOIN retail.dim_customers AS dc
		ON fs.customer_key = dc.customer_key
	GROUP BY dc.customer_id, dc.first_name, dc.last_name
	ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
	SELECT dc.country, SUM(fc.quantity) AS total_sold_items
	FROM retail.fact_sales AS fc
	INNER JOIN retail.dim_customers AS dc
		ON fc.customer_key = dc.customer_key
	GROUP BY dc.country
	ORDER BY total_sold_items DESC

-- =================
-- Ranking Analysis
-- =================

-- Using Window Functions
-- Find the Top 10 customers who have generated the highest revenue
	SELECT *
	FROM(
	SELECT dc.customer_key, dc.first_name, dc.last_name,
	SUM(sales_amount) AS total_revenue,
	RANK() OVER(ORDER BY SUM(sales_amount) DESC) AS rank_sales
	FROM retail.dim_customers AS dc
	LEFT JOIN retail.fact_sales AS fs
		ON dc.customer_key = fs.customer_key
	GROUP BY dc.customer_key, dc.first_name, dc.last_name
	) AS Top_Ten_Customers_High_Rev
	WHERE rank_sales <= 10

-- Find 3 customers with the fewest orders placed
	SELECT TOP 3 dc.customer_key, dc.first_name, dc.last_name,
	COUNT(DISTINCT fs.order_number) AS total_orders
	FROM retail.dim_customers AS dc
	LEFT JOIN retail.fact_sales AS fs
		ON dc.customer_key = fs.customer_key
	GROUP BY dc.customer_key, dc.first_name, dc.last_name
	ORDER BY total_orders ASC